package builder.enumeration;

public enum Topping {
    HAM, RAW_HAM, MORTADELLA, TOMATOES, POTATOES, ONIONS, TUNA, ANCHOVIES, PEPPERONI,
    CHILI, LETTUCE, MOZZARELLA, PARMESAN, SAUCE, BURRATA, BASIL, WURSTEL, FRIES,
    CHEDDAR, CHEESE, OREGANO, GARLIC, OIL, ROCKET_SALAD
}
